# Generated by Django 6.0.2 on 2026-02-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_employee_password_alter_attendancelog_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
